# DO SOMETHING
# 2 Stages
# Build
# Dev

FROM rust:1.76-buster as Build
RUN  cargo new service2
WORKDIR /service2
COPY  ./Cargo.toml .
COPY  ./src/main.rs .
RUN cargo build --release \
    && rm src/*.rs

ADD . ./
RUN cargo build --release 


FROM debian:buster-slim as Dev

ARG APP=/usr/src/app

RUN apt-get update && apt-get install -y ca-certificates 

EXPOSE 8081

ENV APP_USER=appuser

RUN groupadd $APP_USER && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=Build /service2/target/release/service2 ${APP}/service2

RUN chown -R $APP_USER:$APP_USER ${APP}

USER ${APP_USER}

WORKDIR ${APP}

CMD ["./service2"]