

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-VERSION
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: service1
      version: "VERSION"
  template:
    metadata:
      labels:
        name: service1
        version: "VERSION"
    spec:
      containers:
      - name: service1
        image: "asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/images/service1:VERSION"
        ports:
        - name: http
          containerPort: 8080
        

---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
    name: service1
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    name: service1
    version: "VERSION"
    type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2-VERSION
spec:
  replicas: 1
  selector:
    matchLabels: 
      name: service2
      version: "VERSION"
  template:
    metadata:
      labels:
        name: service2
        version: "VERSION"
    spec:
      containers:
      - name: service2
        image: "asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/images/service2:VERSION"
        ports:
        - name: http
          containerPort: 8081
        

---

apiVersion: v1
kind: Service
metadata:
  name: service2
  labels:
    name: service2
spec:
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  selector:
    name: service2
    version: "VERSION"
    type: LoadBalancer
