# Write Docker Compose for services1

version: '3.8'
services:
  service1:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    image: service1:production
    networks:
      - pleno-network
    ports:
      - 8080:8080
    user: "${APP_USER}"
    command: ["./service1"]

networks:
  pleno-network:
    driver: bridge
