# Write Docker Compose for services1

version: '3.8'
services:
  service1:
    build:
      context: /service1
    container_name: service1-production  
    image: service1-production
    networks:
      - pleno-network
    ports:
      - 8080:8080
    command: ["./service1"]
    
networks:
  pleno-network:
    driver: bridge
    external: true
